"""empty message

Revision ID: f206502908e1
Revises: 
Create Date: 2018-07-09 17:50:21.294541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f206502908e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('first_video')
    op.drop_table('game_rank')
    op.drop_table('mode_phone')
    op.drop_table('images')
    op.drop_table('recent_game')
    op.drop_table('hot_news')
    op.drop_table('detail_news')
    op.drop_table('qie_video')
    op.drop_table('mode_game')
    op.drop_table('today_news')
    op.drop_table('game_video')
    op.drop_table('firm_news')
    op.drop_table('WY_news')
    op.drop_table('mod_person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_person',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('photo', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('WY_news',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('remark', mysql.TEXT(), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('firm_news',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('game_video',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('photo', mysql.TEXT(), nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('author', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('index', mysql.TEXT(), nullable=True),
    sa.Column('number', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('today_news',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('text', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('image', mysql.TEXT(), nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('author', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('mode_game',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('clss', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('qie_video',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('pictrue', mysql.TEXT(), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('detail_news',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('image', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('hot_news',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('data', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('recent_game',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('test_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('game_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('test_style', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('download_url', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('images',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('mode_phone',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('create_time', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('game_rank',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('rank', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('game_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('number', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('first_video',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('photo', mysql.TEXT(), nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('author', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('answer')
    op.drop_table('question')
    # ### end Alembic commands ###
